apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstore
  namespace: onlinebookstore

spec:
  replicas: 2

  selector:
    matchLabels:
      app: onlinebookstore

  template:
    metadata:
      labels:
        app: onlinebookstore

    spec:
      containers:
        - name: onlinebookstore

          image: logan7879/onlinebookstore:4c9cdeb1eaac8338c35b4f9216d5f86aa29a40aa

          ports:
            - containerPort: 8080
